name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e ".[dev]"

    - name: Lint
      run: |
        source .venv/bin/activate
        black --check src/
        isort --check-only src/
        ruff check src/

    - name: Type check
      run: |
        source .venv/bin/activate
        mypy src/

    - name: Test
      run: |
        source .venv/bin/activate
        pytest tests/ --cov=src/github_auth_app --cov-report=xml

    - name: Build Docker image
      run: docker build -t github-app-auth:test .
