name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build dev Docker image
      run: docker build -f dev.Dockerfile -t github-app-auth:dev .

    - name: Lint
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app github-app-auth:dev \
          bash -c "black --check src/ && isort --check-only src/ && ruff check src/"

    - name: Type check
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app github-app-auth:dev \
          bash -c "mypy src/"

    - name: Test
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app github-app-auth:dev \
          bash -c "export PYTHONPATH=. && pytest tests/ --cov=src/github_auth_app --cov-report=xml"
