name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v2
        with:
          artifact: test-results
          name: Pytest Results
          path: 'pytest-results.xml'
          reporter: java-junit
          use-actions-summary: 'true'
          fail-on-error: 'true'
          fail-on-empty: 'true'